### ISSUE TITLE
Global menu in KDE Plasma

### ISSUE THREAD

**Issue by ilzeen** [g-fb/haruna#2]
Can you please support KDE plasma global menu applet?

**Comment by g-fb** [comment]
Sorry, for not replying.
It's possible but global menu in QML is a different component from the normal menu.
I have to find a way to do it without duplicating the existing menu.

**Comment by zkvsky** [comment]
@g-fb Or just collapse it into toolbar icon, possibly replacing the 'Configure ' one, it seems to be a common way to deal with that since majority of those [QML, e.g.. [Elisa](https://elisa.kde.org/), [Cinema](https://invent.kde.org/maui/cinema), players ] apps are convergent.
It's an unnecessary eyesore, there's really no need to replicate old paradigms.

Edit. Just noticed that you're already doing that, as there's option for hiding and collapsing into the cog

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.

**Comment by g-fb** [comment]
https://bugs.kde.org/show_bug.cgi?id=436881
